import { Capacitor } from "@capacitor/core";
import { Filesystem, Directory, Encoding } from "@capacitor/filesystem";
import { Share } from "@capacitor/share";

interface DownloadOptions {
  filename: string;
  mimeType: string;
  data: string | Blob | ArrayBuffer;
  shareTitle?: string;
}

/**
 * Checks if we're running in a Capacitor native environment
 */
export const isCapacitorNative = (): boolean => {
  return Capacitor.isNativePlatform();
};

/**
 * Converts data to base64 string for Capacitor Filesystem
 */
const toBase64 = async (data: string | Blob | ArrayBuffer): Promise<string> => {
  if (typeof data === "string") {
    // If it's already a data URL, extract base64
    if (data.startsWith("data:")) {
      return data.split(",")[1];
    }
    // Plain string, convert to base64
    return btoa(data);
  }
  
  if (data instanceof Blob) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64 = (reader.result as string).split(",")[1];
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(data);
    });
  }
  
  if (data instanceof ArrayBuffer) {
    const bytes = new Uint8Array(data);
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  
  throw new Error("Unsupported data type");
};

/**
 * Downloads a file - works on both web and Capacitor native
 */
export const downloadFile = async (options: DownloadOptions): Promise<{ success: boolean; path?: string; error?: string }> => {
  const { filename, mimeType, data, shareTitle } = options;
  
  if (isCapacitorNative()) {
    try {
      const base64Data = await toBase64(data);
      
      // Save to Downloads directory on Android or Documents on iOS
      const result = await Filesystem.writeFile({
        path: filename,
        data: base64Data,
        directory: Directory.Documents,
        recursive: true,
      });
      
      // Try to share the file so the user can open it or save it elsewhere
      try {
        await Share.share({
          title: shareTitle || filename,
          url: result.uri,
          dialogTitle: `Guardar ${filename}`,
        });
      } catch (shareError) {
        // Share might fail if user cancels, but file is still saved
        console.log("Share cancelled or failed:", shareError);
      }
      
      return { success: true, path: result.uri };
    } catch (error) {
      console.error("Error saving file on native:", error);
      return { success: false, error: String(error) };
    }
  } else {
    // Web browser download
    try {
      let blob: Blob;
      
      if (data instanceof Blob) {
        blob = data;
      } else if (data instanceof ArrayBuffer) {
        blob = new Blob([data], { type: mimeType });
      } else if (typeof data === "string") {
        if (data.startsWith("data:")) {
          // Data URL
          const response = await fetch(data);
          blob = await response.blob();
        } else {
          // Plain string
          blob = new Blob([data], { type: mimeType });
        }
      } else {
        throw new Error("Unsupported data type");
      }
      
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      return { success: true };
    } catch (error) {
      console.error("Error downloading file on web:", error);
      return { success: false, error: String(error) };
    }
  }
};

/**
 * Saves a PDF document generated by jsPDF
 */
export const savePDF = async (doc: any, filename: string): Promise<{ success: boolean; path?: string; error?: string }> => {
  if (isCapacitorNative()) {
    // Get PDF as blob
    const pdfBlob = doc.output("blob");
    
    return downloadFile({
      filename,
      mimeType: "application/pdf",
      data: pdfBlob,
      shareTitle: `Documento PDF: ${filename}`,
    });
  } else {
    // Use jsPDF's built-in save on web
    doc.save(filename);
    return { success: true };
  }
};

/**
 * Saves an Excel workbook generated by XLSX
 */
export const saveExcel = async (workbook: any, filename: string, XLSX: any): Promise<{ success: boolean; path?: string; error?: string }> => {
  if (isCapacitorNative()) {
    // Get Excel as array buffer
    const excelBuffer = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    
    return downloadFile({
      filename,
      mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      data: excelBuffer,
      shareTitle: `Ficheiro Excel: ${filename}`,
    });
  } else {
    // Use XLSX's built-in writeFile on web
    XLSX.writeFile(workbook, filename);
    return { success: true };
  }
};
